import type { ImportedPentestCapability } from '../types.js'

export const API_PACK_TOOLS: ImportedPentestCapability[] = [
  {
    id: "kali-graphql-scanner" as const,
    label: "GraphQL Scanner",
    description: "GraphQL introspection and mutation vulnerability scanning capability for API attack surface.",
    capabilityPacks: ["api","web","exploitation"],
    recommendedAgents: ["app-testing-specialist","app-testing-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["python3"],
  },
  {
    id: "kali-jwt-tool" as const,
    label: "JWT Attack Toolkit",
    description: "JWT token analysis and attack capability for alg:none, key confusion, and brute-force attacks.",
    capabilityPacks: ["api","web","exploitation"],
    recommendedAgents: ["app-testing-specialist","app-testing-specialist","infra-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["python3"],
  },
  {
    id: "kali-api-schema-analyzer" as const,
    label: "API Schema Security Analyzer",
    description: "Analyze OpenAPI/Swagger/GraphQL schemas for security issues including auth gaps, injection points, and misconfigurations.",
    capabilityPacks: ["api","web"],
    recommendedAgents: ["app-testing-specialist","app-testing-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["curl"],
  },
  {
    id: "kali-schemathesis" as const,
    label: "Schemathesis OpenAPI Fuzzer",
    description: "Property-based fuzzer for OpenAPI and GraphQL APIs that auto-generates adversarial test cases from the schema to surface crashes, 5xx errors, and contract violations.",
    capabilityPacks: ["api","web","exploitation"],
    recommendedAgents: ["app-testing-specialist","app-testing-specialist","infra-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["schemathesis"],
    mitreAttackTechniques: ["T1190"],
  },
  {
    id: "kali-restler-fuzzer" as const,
    label: "RESTler Stateful REST Fuzzer",
    description: "Microsoft's stateful REST API fuzzer that infers resource dependencies from an OpenAPI spec and sequences requests to discover logic bugs and security vulnerabilities.",
    capabilityPacks: ["api","exploitation"],
    recommendedAgents: ["app-testing-specialist","infra-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["Restler"],
    mitreAttackTechniques: ["T1190"],
  },
  {
    id: "kali-kiterunner" as const,
    label: "Kiterunner API Route Brute-Forcer",
    description: "High-speed API content-discovery tool that replays Swagger and Postman wordlists against target hosts to enumerate undocumented endpoints and hidden routes.",
    capabilityPacks: ["api","recon","web"],
    recommendedAgents: ["app-testing-specialist","recon-specialist","app-testing-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["kr"],
    mitreAttackTechniques: ["T1595.003"],
  },
  {
    id: "kali-graphw00f" as const,
    label: "graphw00f GraphQL Fingerprinter",
    description: "GraphQL engine fingerprinting tool that identifies the backend technology (Apollo, Hasura, AWS AppSync, etc.) by analyzing error messages and behavioural differences.",
    capabilityPacks: ["api","recon","web"],
    recommendedAgents: ["app-testing-specialist","recon-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["python3"],
    mitreAttackTechniques: ["T1592"],
  },
  {
    id: "kali-graphql-cop" as const,
    label: "GraphQL Cop Security Auditor",
    description: "Automated GraphQL security audit tool that checks for introspection exposure, DoS vectors, CSRF, field-level auth gaps, and information-leakage issues across 12 test categories.",
    capabilityPacks: ["api","web","exploitation"],
    recommendedAgents: ["app-testing-specialist","app-testing-specialist","infra-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["python3"],
    mitreAttackTechniques: ["T1190"],
  },
  {
    id: "kali-clairvoyance" as const,
    label: "Clairvoyance GraphQL Schema Extractor",
    description: "Recovers GraphQL schemas from targets with introspection disabled by using wordlist-guided field suggestion, enabling attack-surface mapping on hardened GraphQL APIs.",
    capabilityPacks: ["api","recon","web"],
    recommendedAgents: ["app-testing-specialist","recon-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["clairvoyance"],
    mitreAttackTechniques: ["T1592"],
  },
  {
    id: "kali-inql" as const,
    label: "InQL GraphQL Security Scanner",
    description: "GraphQL introspection scanner and Burp Suite extension that auto-generates queries and mutations, detects batch attack vectors, and fingerprints backend engines.",
    capabilityPacks: ["api","web","exploitation"],
    recommendedAgents: ["app-testing-specialist","app-testing-specialist","infra-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["python3"],
    mitreAttackTechniques: ["T1592"],
  },
  {
    id: "kali-mitmproxy" as const,
    label: "mitmproxy TLS-Aware HTTP Proxy",
    description: "Interactive TLS-capable intercepting proxy with scripting API used for API traffic capture, replay, and on-the-fly request manipulation during API security assessments.",
    capabilityPacks: ["api","web","exploitation"],
    recommendedAgents: ["app-testing-specialist","app-testing-specialist","infra-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["mitmproxy"],
    mitreAttackTechniques: ["T1557"],
  },
  {
    id: "kali-postman-newman" as const,
    label: "Newman Postman Collection Runner",
    description: "CLI runner for Postman collections used to execute API regression and security test suites, replay authenticated request sequences, and validate API behaviour changes.",
    capabilityPacks: ["api","web"],
    recommendedAgents: ["app-testing-specialist","app-testing-specialist","evidence-reporting-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["newman"],
    mitreAttackTechniques: ["T1190"],
  },
]
