import type { ImportedPentestCapability } from '../types.js'

export const BINARY_PACK_TOOLS: ImportedPentestCapability[] = [
  {
    id: "kali-pwntools" as const,
    label: "Pwntools Exploit Development",
    description: "Binary exploitation scripting capability for exploit validation in challenge/lab targets.",
    capabilityPacks: ["binary","exploitation"],
    recommendedAgents: ["binary-specialist","exploit-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["python3"],
  },
  {
    id: "kali-volatility3" as const,
    label: "Volatility3 Memory Forensics",
    description: "Memory forensics capability for process, handle, and artifact analysis in incident scenarios.",
    capabilityPacks: ["binary","evidence","recon"],
    recommendedAgents: ["evidence-specialist","recon-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["volatility3"],
  },
  {
    id: "kali-foremost" as const,
    label: "Foremost File Carving",
    description: "File carving capability for artifact recovery and evidence extraction.",
    capabilityPacks: ["binary","evidence"],
    recommendedAgents: ["evidence-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["foremost"],
  },
  {
    id: "kali-binwalk" as const,
    label: "Binwalk Firmware Analysis",
    description: "Firmware extraction and binary artifact analysis capability for embedded target workflows.",
    capabilityPacks: ["binary","recon","exploitation"],
    recommendedAgents: ["binary-specialist","exploit-specialist","recon-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["binwalk"],
  },
  {
    id: "kali-steghide" as const,
    label: "Steghide Analysis",
    description: "Steganography extraction capability for challenge and forensic artifact analysis.",
    capabilityPacks: ["binary","evidence"],
    recommendedAgents: ["exploit-specialist","evidence-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["steghide"],
  },
  {
    id: "kali-ghidra" as const,
    label: "Ghidra Reverse Engineering",
    description: "Reverse engineering capability for static binary analysis and function-level review.",
    capabilityPacks: ["binary","exploitation"],
    recommendedAgents: ["binary-specialist","exploit-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["ghidraRun"],
  },
  {
    id: "kali-radare2" as const,
    label: "Radare2 Analysis",
    description: "Command-line reverse engineering capability for binary triage and analysis.",
    capabilityPacks: ["binary","exploitation"],
    recommendedAgents: ["binary-specialist","exploit-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["radare2"],
  },
  {
    id: "kali-gdb" as const,
    label: "GDB Debugging",
    description: "Runtime debugger capability for controlled binary behavior analysis and exploit validation.",
    capabilityPacks: ["binary","exploitation"],
    recommendedAgents: ["binary-specialist","exploit-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["gdb"],
  },
  {
    id: "kali-checksec" as const,
    label: "Checksec Hardening Analysis",
    description: "Binary hardening inspection capability for exploitability triage and mitigation assessment.",
    capabilityPacks: ["binary","exploitation"],
    recommendedAgents: ["binary-specialist","exploit-specialist","recon-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Read"],
    requiredCommands: ["checksec"],
  },
  {
    id: "kali-ropgadget" as const,
    label: "ROPGadget Discovery",
    description: "ROP gadget discovery capability for exploit development workflows.",
    capabilityPacks: ["binary","exploitation"],
    recommendedAgents: ["binary-specialist","exploit-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["ROPgadget"],
  },
  {
    id: "kali-ropper" as const,
    label: "Ropper Gadget Discovery",
    description: "Alternative ROP gadget discovery capability for binary exploit-chain construction.",
    capabilityPacks: ["binary","exploitation"],
    recommendedAgents: ["binary-specialist","exploit-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["ropper"],
  },
  {
    id: "kali-one-gadget" as const,
    label: "One-Gadget Discovery",
    description: "One-gadget libc exploit primitive discovery capability.",
    capabilityPacks: ["binary","exploitation"],
    recommendedAgents: ["binary-specialist","exploit-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["one_gadget"],
  },
  {
    id: "kali-angr" as const,
    label: "Angr Symbolic Analysis",
    description: "Symbolic execution analysis capability for binary path solving and exploit development.",
    capabilityPacks: ["binary","exploitation"],
    recommendedAgents: ["binary-specialist","exploit-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["python3"],
  },
  {
    id: "kali-photorec" as const,
    label: "PhotoRec File Recovery",
    description: "File recovery capability for carving deleted files from disk images and drives.",
    capabilityPacks: ["binary","evidence"],
    recommendedAgents: ["evidence-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["photorec"],
  },
  {
    id: "kali-scalpel" as const,
    label: "Scalpel File Carving",
    description: "Configurable file carving capability with header/footer-based artifact recovery.",
    capabilityPacks: ["binary","evidence"],
    recommendedAgents: ["evidence-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["scalpel"],
  },
  {
    id: "kali-zsteg" as const,
    label: "Zsteg Steganography",
    description: "PNG/BMP steganography detection and extraction capability for challenge and forensic analysis.",
    capabilityPacks: ["binary","evidence"],
    recommendedAgents: ["exploit-specialist","evidence-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["zsteg"],
  },
  {
    id: "kali-sleuthkit" as const,
    label: "The Sleuth Kit",
    description: "Command-line digital forensics toolkit capability for disk image analysis (fls, icat, mmls).",
    capabilityPacks: ["binary","evidence"],
    recommendedAgents: ["evidence-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["fls"],
  },
  {
    id: "kali-autopsy" as const,
    label: "Autopsy Forensics Platform",
    description: "Digital forensics platform capability for disk image analysis and artifact triage.",
    capabilityPacks: ["binary","evidence"],
    recommendedAgents: ["evidence-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["autopsy"],
  },
  {
    id: "kali-hashpump" as const,
    label: "HashPump Length Extension",
    description: "Hash length extension attack capability for exploiting vulnerable HMAC implementations.",
    capabilityPacks: ["binary","exploitation"],
    recommendedAgents: ["binary-specialist","exploit-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["hashpump"],
  },
  {
    id: "kali-objdump" as const,
    label: "Objdump Disassembly",
    description: "Binary disassembly and object file inspection capability for quick static analysis.",
    capabilityPacks: ["binary","exploitation"],
    recommendedAgents: ["binary-specialist","exploit-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["objdump"],
  },
  {
    id: "kali-libc-database" as const,
    label: "Libc Database Lookup",
    description: "Libc version identification capability by symbol offsets for binary exploitation workflows.",
    capabilityPacks: ["binary","exploitation"],
    recommendedAgents: ["binary-specialist","exploit-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["python3"],
  },
  {
    id: "kali-pwninit" as const,
    label: "PwnInit CTF Setup",
    description: "CTF binary patching capability for libc linking and exploit template generation.",
    capabilityPacks: ["binary","exploitation"],
    recommendedAgents: ["binary-specialist","exploit-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["pwninit"],
  },
]
