import type { ImportedPentestCapability } from '../types.js'

export const CLOUD_PACK_TOOLS: ImportedPentestCapability[] = [
  {
    id: "kali-trivy" as const,
    label: "Trivy Vulnerability Scanning",
    description: "Container and filesystem vulnerability scanning capability for cloud and CI targets.",
    capabilityPacks: ["cloud","lab-control","reporting"],
    recommendedAgents: ["recon-specialist","reporting-specialist","evidence-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["trivy"],
  },
  {
    id: "kali-docker-bench" as const,
    label: "Docker Bench Hardening",
    description: "Container host hardening assessment capability based on Docker benchmark checks.",
    capabilityPacks: ["cloud","lab-control","reporting"],
    recommendedAgents: ["recon-specialist","reporting-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["docker-bench-security"],
  },
  {
    id: "kali-checkov" as const,
    label: "Checkov IaC Scanning",
    description: "Infrastructure-as-code static analysis capability for cloud misconfiguration discovery.",
    capabilityPacks: ["cloud","reporting"],
    recommendedAgents: ["recon-specialist","reporting-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["checkov"],
  },
  {
    id: "kali-terrascan" as const,
    label: "Terrascan IaC Scanning",
    description: "IaC policy and compliance scanning capability for Terraform/Kubernetes/security checks.",
    capabilityPacks: ["cloud","reporting"],
    recommendedAgents: ["recon-specialist","reporting-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["terrascan"],
  },
  {
    id: "kali-prowler" as const,
    label: "Prowler Cloud Auditing",
    description: "Cloud security auditing capability for AWS/GCP/Azure benchmark checks.",
    capabilityPacks: ["cloud","reporting"],
    recommendedAgents: ["recon-specialist","reporting-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["prowler"],
  },
  {
    id: "kali-scout-suite" as const,
    label: "ScoutSuite Cloud Auditing",
    description: "Multi-cloud posture assessment capability for account-level risk visibility.",
    capabilityPacks: ["cloud","reporting"],
    recommendedAgents: ["recon-specialist","reporting-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["scout"],
  },
  {
    id: "kali-kube-bench" as const,
    label: "Kube-Bench Assessment",
    description: "Kubernetes benchmark scanning capability for cluster hardening and compliance checks.",
    capabilityPacks: ["cloud","network","reporting"],
    recommendedAgents: ["network-testing-specialist","reporting-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["kube-bench"],
  },
  {
    id: "kali-kube-hunter" as const,
    label: "Kube-Hunter Assessment",
    description: "Kubernetes attack-surface hunting capability for exposed cluster services and controls.",
    capabilityPacks: ["cloud","network","recon"],
    recommendedAgents: ["network-testing-specialist","recon-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["kube-hunter"],
  },
  {
    id: "kali-pacu" as const,
    label: "Pacu Cloud Exploitation",
    description: "Cloud exploitation framework capability for controlled attack-path validation in AWS.",
    capabilityPacks: ["cloud","exploitation","lab-control"],
    recommendedAgents: ["exploit-specialist","recon-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["pacu"],
  },
  {
    id: "kali-cloudmapper" as const,
    label: "CloudMapper Visualization",
    description: "Cloud relationship and exposure visualization capability for attack-path planning.",
    capabilityPacks: ["cloud","recon","reporting"],
    recommendedAgents: ["recon-specialist","reporting-specialist","engagement-lead"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["cloudmapper"],
  },
  {
    id: "kali-cloud-enum" as const,
    label: "Cloud Enum External Enumeration",
    description: "Unauthenticated cloud asset enumeration capability for buckets, blobs, apps, and naming-pattern exposure checks.",
    capabilityPacks: ["cloud","recon"],
    recommendedAgents: ["recon-specialist","network-testing-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebSearch","TodoWrite","Write","Read"],
    requiredCommands: ["cloud_enum"],
  },
  {
    id: "kali-clair" as const,
    label: "Clair Container Scanner",
    description: "Container vulnerability scanner capability for static OCI/Docker image analysis.",
    capabilityPacks: ["cloud"],
    recommendedAgents: ["recon-specialist","reporting-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["clair-scanner"],
  },
  {
    id: "kali-falco" as const,
    label: "Falco Runtime Monitoring",
    description: "Runtime security monitoring capability for detecting anomalous container and host behaviour.",
    capabilityPacks: ["cloud","evidence"],
    recommendedAgents: ["recon-specialist","evidence-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["falco"],
  },
]
