import type { ImportedPentestCapability } from '../types.js'

export const CODE_AUDIT_PACK_TOOLS: ImportedPentestCapability[] = [
  {
    id: 'kali-semgrep' as const,
    label: 'Semgrep',
    description: 'Multi-language SAST engine. Run `semgrep --config auto --sarif -o semgrep.sarif .` for rule-set-driven pattern matching across Python, JS/TS, Go, Java, Ruby, and 30+ languages. Supports custom rules and SARIF output for pipeline integration.',
    capabilityPacks: ['code-audit', 'evidence'],
    recommendedAgents: ['code-forensics-specialist', 'evidence-reporting-specialist'],
    executionModel: 'skills-and-tools',
    netRunnerTools: ['Bash', 'Read', 'Write', 'TodoWrite', 'Grep', 'Glob'],
    requiredCommands: ['semgrep'],
    mitreAttackTechniques: ['T1059', 'T1190'],
  },
  {
    id: 'kali-bandit' as const,
    label: 'Bandit',
    description: 'Python-specific SAST tool from PyCQA. Run `bandit -r . -f sarif -o bandit.sarif` to detect common security issues including hardcoded credentials, SQL injection, shell injection, and insecure deserialization in Python codebases.',
    capabilityPacks: ['code-audit', 'evidence'],
    recommendedAgents: ['code-forensics-specialist', 'evidence-reporting-specialist'],
    executionModel: 'skills-and-tools',
    netRunnerTools: ['Bash', 'Read', 'Write', 'TodoWrite', 'Grep', 'Glob'],
    requiredCommands: ['bandit'],
    mitreAttackTechniques: ['T1059.006', 'T1190'],
  },
  {
    id: 'kali-gosec' as const,
    label: 'gosec',
    description: 'Go security checker by Securego. Run `gosec -fmt sarif -out gosec.sarif ./...` to inspect Go AST for security issues including SQL injection, command injection, crypto weaknesses, and file path traversal. Maps findings to CWE identifiers.',
    capabilityPacks: ['code-audit', 'evidence'],
    recommendedAgents: ['code-forensics-specialist', 'evidence-reporting-specialist'],
    executionModel: 'skills-and-tools',
    netRunnerTools: ['Bash', 'Read', 'Write', 'TodoWrite', 'Grep', 'Glob'],
    requiredCommands: ['gosec'],
    mitreAttackTechniques: ['T1059', 'T1190'],
  },
  {
    id: 'kali-gitleaks' as const,
    label: 'Gitleaks',
    description: 'Secret detection tool for git repositories. Run `gitleaks detect --report-format sarif --report-path gitleaks.sarif` to scan commit history and working tree for API keys, tokens, passwords, and private keys. Supports baseline mode to suppress known findings.',
    capabilityPacks: ['code-audit', 'evidence'],
    recommendedAgents: ['code-forensics-specialist', 'evidence-reporting-specialist'],
    executionModel: 'skills-and-tools',
    netRunnerTools: ['Bash', 'Read', 'Write', 'TodoWrite', 'Grep', 'Glob'],
    requiredCommands: ['gitleaks'],
    mitreAttackTechniques: ['T1552', 'T1552.001'],
  },
  {
    id: 'kali-noseyparker' as const,
    label: 'Nosey Parker',
    description: 'High-recall secret scanner with vectorized regex engine. Run `noseyparker scan --datastore ./np-ds .` then `noseyparker report --datastore ./np-ds` to detect credentials, tokens, and sensitive patterns across source trees and blobs with low false-positive tuning.',
    capabilityPacks: ['code-audit', 'evidence'],
    recommendedAgents: ['code-forensics-specialist', 'evidence-reporting-specialist'],
    executionModel: 'skills-and-tools',
    netRunnerTools: ['Bash', 'Read', 'Write', 'TodoWrite', 'Grep', 'Glob'],
    requiredCommands: ['noseyparker'],
    mitreAttackTechniques: ['T1552', 'T1552.001'],
  },
  {
    id: 'kali-trivy' as const,
    label: 'Trivy',
    description: 'Comprehensive vulnerability and misconfiguration scanner by Aqua Security. Run `trivy fs --scanners vuln,secret,misconfig --format sarif -o trivy.sarif .` for filesystem scans; `trivy image --format sarif` for container images. Detects OS/library CVEs, secrets, and IaC issues.',
    capabilityPacks: ['code-audit', 'evidence'],
    recommendedAgents: ['code-forensics-specialist', 'evidence-reporting-specialist'],
    executionModel: 'skills-and-tools',
    netRunnerTools: ['Bash', 'Read', 'Write', 'TodoWrite', 'Grep', 'Glob'],
    requiredCommands: ['trivy'],
    mitreAttackTechniques: ['T1190', 'T1552'],
  },
  {
    id: 'kali-checkov' as const,
    label: 'Checkov',
    description: 'IaC static analysis tool by Bridgecrew. Run `checkov -d . -o sarif` to audit Terraform, CloudFormation, Kubernetes, Helm, ARM, Bicep, Dockerfile, and Serverless Framework configurations for security misconfigurations against 1000+ built-in policies.',
    capabilityPacks: ['code-audit', 'evidence'],
    recommendedAgents: ['code-forensics-specialist', 'evidence-reporting-specialist'],
    executionModel: 'skills-and-tools',
    netRunnerTools: ['Bash', 'Read', 'Write', 'TodoWrite', 'Grep', 'Glob'],
    requiredCommands: ['checkov'],
    mitreAttackTechniques: ['T1190', 'T1078'],
  },
  {
    id: 'kali-tfsec' as const,
    label: 'tfsec',
    description: 'Terraform-focused static analysis tool. Run `tfsec . --format sarif --out tfsec.sarif` to detect misconfigured AWS, Azure, GCP, and Kubernetes Terraform resources. Checks encryption, public exposure, IAM over-permission, and logging gaps.',
    capabilityPacks: ['code-audit', 'evidence'],
    recommendedAgents: ['code-forensics-specialist', 'evidence-reporting-specialist'],
    executionModel: 'skills-and-tools',
    netRunnerTools: ['Bash', 'Read', 'Write', 'TodoWrite', 'Grep', 'Glob'],
    requiredCommands: ['tfsec'],
    mitreAttackTechniques: ['T1190', 'T1078'],
  },
  {
    id: 'kali-kics' as const,
    label: 'KICS (Keeping Infrastructure as Code Secure)',
    description: 'Open-source IaC scanner by Checkmarx. Run `kics scan -p . -o ./kics-report --report-formats sarif` to detect misconfigurations in Terraform, Ansible, CloudFormation, Docker Compose, Kubernetes, and 20+ other IaC frameworks.',
    capabilityPacks: ['code-audit', 'evidence'],
    recommendedAgents: ['code-forensics-specialist', 'evidence-reporting-specialist'],
    executionModel: 'skills-and-tools',
    netRunnerTools: ['Bash', 'Read', 'Write', 'TodoWrite', 'Grep', 'Glob'],
    requiredCommands: ['kics'],
    mitreAttackTechniques: ['T1190', 'T1078'],
  },
  {
    id: 'kali-dependency-check' as const,
    label: 'OWASP Dependency-Check',
    description: 'Software composition analysis tool by OWASP. Run `dependency-check --scan . --format SARIF --out ./dependency-check.sarif` to identify known CVEs in Java, .NET, JavaScript, Ruby, and Python dependencies via NVD, OSS Index, and RetireJS data sources.',
    capabilityPacks: ['code-audit', 'evidence'],
    recommendedAgents: ['code-forensics-specialist', 'evidence-reporting-specialist'],
    executionModel: 'skills-and-tools',
    netRunnerTools: ['Bash', 'Read', 'Write', 'TodoWrite', 'Grep', 'Glob'],
    requiredCommands: ['dependency-check'],
    mitreAttackTechniques: ['T1190', 'T1203'],
  },
  {
    id: 'kali-retire-js' as const,
    label: 'Retire.js',
    description: 'JavaScript dependency vulnerability scanner. Run `retire --outputformat json --outputpath retire.json` to detect client-side and Node.js libraries with known CVEs. Integrates with npm projects and scans bundled JS files for vulnerable library signatures.',
    capabilityPacks: ['code-audit', 'evidence'],
    recommendedAgents: ['code-forensics-specialist', 'evidence-reporting-specialist'],
    executionModel: 'skills-and-tools',
    netRunnerTools: ['Bash', 'Read', 'Write', 'TodoWrite', 'Grep', 'Glob'],
    requiredCommands: ['retire'],
    mitreAttackTechniques: ['T1190', 'T1203'],
  },
  {
    id: 'kali-npm-audit' as const,
    label: 'npm audit',
    description: 'Built-in Node.js dependency vulnerability auditor. Run `npm audit --json` (binary: `npm`) to query the npm advisory database for known vulnerabilities in project dependencies and devDependencies. Provides fix guidance and severity classification per advisory.',
    capabilityPacks: ['code-audit', 'evidence'],
    recommendedAgents: ['code-forensics-specialist', 'evidence-reporting-specialist'],
    executionModel: 'skills-and-tools',
    netRunnerTools: ['Bash', 'Read', 'Write', 'TodoWrite', 'Grep', 'Glob'],
    requiredCommands: ['npm'],
    mitreAttackTechniques: ['T1190', 'T1203'],
  },
  {
    id: 'kali-pip-audit' as const,
    label: 'pip-audit',
    description: 'Python package vulnerability auditor by PyPA. Run `pip-audit -f json -o pip-audit.json` to scan installed packages or requirements files against the Python Advisory Database (PyPI) and OSV. Supports SBOM input and virtual environment scanning.',
    capabilityPacks: ['code-audit', 'evidence'],
    recommendedAgents: ['code-forensics-specialist', 'evidence-reporting-specialist'],
    executionModel: 'skills-and-tools',
    netRunnerTools: ['Bash', 'Read', 'Write', 'TodoWrite', 'Grep', 'Glob'],
    requiredCommands: ['pip-audit'],
    mitreAttackTechniques: ['T1190', 'T1203'],
  },
  {
    id: 'kali-govulncheck' as const,
    label: 'govulncheck',
    description: 'Go vulnerability checker by the Go security team. Run `govulncheck -json ./...` to report known vulnerabilities in Go module dependencies by cross-referencing the Go vulnerability database (vuln.go.dev). Only flags vulnerabilities reachable via call graph analysis, reducing noise.',
    capabilityPacks: ['code-audit', 'evidence'],
    recommendedAgents: ['code-forensics-specialist', 'evidence-reporting-specialist'],
    executionModel: 'skills-and-tools',
    netRunnerTools: ['Bash', 'Read', 'Write', 'TodoWrite', 'Grep', 'Glob'],
    requiredCommands: ['govulncheck'],
    mitreAttackTechniques: ['T1190', 'T1203'],
  },
]
