import type { ImportedPentestCapability } from '../types.js'

export const EVIDENCE_PACK_TOOLS: ImportedPentestCapability[] = [
  {
    id: "kali-exiftool" as const,
    label: "ExifTool Metadata Extraction",
    description: "Metadata extraction capability for evidence, intel, and file artifact profiling.",
    capabilityPacks: ["evidence","recon"],
    recommendedAgents: ["evidence-reporting-specialist","recon-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["exiftool"],
  },
  {
    id: "kali-bulk-extractor" as const,
    label: "Bulk Extractor",
    description: "Feature extraction capability for emails, URLs, credit cards, and artifacts from disk images.",
    capabilityPacks: ["evidence","recon"],
    recommendedAgents: ["evidence-reporting-specialist","recon-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["bulk_extractor"],
  },
  {
    id: "kali-stegsolve" as const,
    label: "StegSolve Image Analysis",
    description: "Steganography analysis tool for visual inspection, bit-plane analysis, and colour channel manipulation.",
    capabilityPacks: ["evidence","binary"],
    recommendedAgents: ["evidence-reporting-specialist","infra-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["stegsolve"],
  },
  {
    id: "kali-outguess" as const,
    label: "OutGuess JPEG Steganography",
    description: "Universal steganographic tool for embedding and extracting hidden data in JPEG images.",
    capabilityPacks: ["evidence"],
    recommendedAgents: ["evidence-reporting-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["outguess"],
  },
  {
    id: "kali-testdisk" as const,
    label: "TestDisk Partition Recovery",
    description: "Disk partition recovery and repair tool for rebuilding boot sectors and recovering deleted partitions.",
    capabilityPacks: ["evidence"],
    recommendedAgents: ["evidence-reporting-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["testdisk"],
  },
]
