import type { ImportedPentestCapability } from '../types.js'

export const FORENSICS_PACK_TOOLS: ImportedPentestCapability[] = [
  {
    id: 'kali-volatility3' as const,
    label: 'Volatility 3',
    description: 'Memory forensics framework for Linux, Windows, and macOS. Extracts process lists, network connections, injected code, and registry hives from RAM dumps.',
    capabilityPacks: ['forensics', 'evidence'],
    recommendedAgents: ['code-forensics-specialist', 'evidence-reporting-specialist'],
    executionModel: 'skills-and-tools',
    netRunnerTools: ['Bash', 'TodoWrite', 'Read', 'Write'],
    requiredCommands: ['vol'],
    mitreAttackTechniques: ['T1003', 'T1057', 'T1049'],
  },
  {
    id: 'kali-plaso' as const,
    label: 'Plaso (log2timeline)',
    description: 'Super-timeline generator. Ingests disk images, log files, and artifact archives via log2timeline.py; exports to L2T CSV with psort.py for timeline analysis.',
    capabilityPacks: ['forensics', 'evidence'],
    recommendedAgents: ['code-forensics-specialist', 'evidence-reporting-specialist'],
    executionModel: 'skills-and-tools',
    netRunnerTools: ['Bash', 'TodoWrite', 'Read', 'Write'],
    requiredCommands: ['log2timeline.py'],
    mitreAttackTechniques: ['T1070', 'T1083'],
  },
  {
    id: 'kali-kape' as const,
    label: 'KAPE (Kroll Artifact Parser and Extractor)',
    description: 'Windows-only triage collector that targets and modules against live or mounted volumes. Run via kape.exe; outputs structured artifact sets for downstream analysis.',
    capabilityPacks: ['forensics', 'evidence'],
    recommendedAgents: ['code-forensics-specialist'],
    executionModel: 'skills-and-tools',
    netRunnerTools: ['Bash', 'TodoWrite', 'Read', 'Write'],
    requiredCommands: ['kape.exe'],
    mitreAttackTechniques: ['T1005', 'T1074'],
  },
  {
    id: 'kali-chainsaw' as const,
    label: 'Chainsaw',
    description: 'Fast Windows EVTX log hunter with built-in Sigma rule support. Run chainsaw hunt against an EVTX directory to surface credential attacks, lateral movement, and execution events.',
    capabilityPacks: ['forensics', 'evidence'],
    recommendedAgents: ['code-forensics-specialist', 'evidence-reporting-specialist'],
    executionModel: 'skills-and-tools',
    netRunnerTools: ['Bash', 'TodoWrite', 'Read', 'Write'],
    requiredCommands: ['chainsaw'],
    mitreAttackTechniques: ['T1070.001', 'T1078', 'T1059'],
  },
  {
    id: 'kali-hayabusa' as const,
    label: 'Hayabusa',
    description: 'Sigma-based Windows event log threat hunting and forensics timeline tool. Produces CSV timelines and JSON alerts from EVTX files with built-in and community Sigma rules.',
    capabilityPacks: ['forensics', 'evidence'],
    recommendedAgents: ['code-forensics-specialist', 'evidence-reporting-specialist'],
    executionModel: 'skills-and-tools',
    netRunnerTools: ['Bash', 'TodoWrite', 'Read', 'Write'],
    requiredCommands: ['hayabusa'],
    mitreAttackTechniques: ['T1070.001', 'T1059', 'T1021'],
  },
  {
    id: 'kali-velociraptor' as const,
    label: 'Velociraptor',
    description: 'Endpoint visibility and digital forensics platform. Run artifact collections (e.g. Windows.KapeFiles.Targets, Linux.Sys.Pslist) via velociraptor artifacts collect for live or offline triage.',
    capabilityPacks: ['forensics', 'evidence', 'coordination'],
    recommendedAgents: ['code-forensics-specialist', 'evidence-reporting-specialist'],
    executionModel: 'skills-and-tools',
    netRunnerTools: ['Bash', 'TodoWrite', 'Read', 'Write'],
    requiredCommands: ['velociraptor'],
    mitreAttackTechniques: ['T1005', 'T1057', 'T1049'],
  },
  {
    id: 'kali-mvt' as const,
    label: 'MVT (Mobile Verification Toolkit)',
    description: 'iOS and Android forensics toolkit for detecting stalkerware and nation-state IOCs. Primary binary mvt-ios for iPhone backups; mvt-android for ADB-connected Android devices.',
    capabilityPacks: ['forensics', 'evidence', 'mobile'],
    recommendedAgents: ['code-forensics-specialist', 'evidence-reporting-specialist'],
    executionModel: 'skills-and-tools',
    netRunnerTools: ['Bash', 'TodoWrite', 'Read', 'Write'],
    requiredCommands: ['mvt-ios'],
    mitreAttackTechniques: ['T1512', 'T1430', 'T1636'],
  },
  {
    id: 'kali-aleapp' as const,
    label: 'ALEAPP (Android Logs Events And Protobuf Parser)',
    description: 'Android artifact parser that extracts and decodes logs, accounts, installed apps, location data, and browser history from Android backups and image extractions.',
    capabilityPacks: ['forensics', 'evidence', 'mobile'],
    recommendedAgents: ['code-forensics-specialist', 'evidence-reporting-specialist'],
    executionModel: 'skills-and-tools',
    netRunnerTools: ['Bash', 'TodoWrite', 'Read', 'Write'],
    requiredCommands: ['aleapp'],
    mitreAttackTechniques: ['T1430', 'T1636'],
  },
  {
    id: 'kali-ileapp' as const,
    label: 'iLEAPP (iOS Logs Events And Plists Parser)',
    description: 'iOS artifact parser that decodes plists, SQLite databases, location data, app usage, and system logs from iTunes/Finder backups and filesystem extractions.',
    capabilityPacks: ['forensics', 'evidence', 'mobile'],
    recommendedAgents: ['code-forensics-specialist', 'evidence-reporting-specialist'],
    executionModel: 'skills-and-tools',
    netRunnerTools: ['Bash', 'TodoWrite', 'Read', 'Write'],
    requiredCommands: ['ileapp'],
    mitreAttackTechniques: ['T1430', 'T1636'],
  },
  {
    id: 'kali-bulk-extractor' as const,
    label: 'bulk_extractor',
    description: 'High-speed feature extraction scanner for disk images and memory dumps. Carves emails, URLs, credit card numbers, domains, and other structured data without mounting the image.',
    capabilityPacks: ['forensics', 'evidence'],
    recommendedAgents: ['code-forensics-specialist', 'evidence-reporting-specialist'],
    executionModel: 'skills-and-tools',
    netRunnerTools: ['Bash', 'TodoWrite', 'Read', 'Write'],
    requiredCommands: ['bulk_extractor'],
    mitreAttackTechniques: ['T1005', 'T1213'],
  },
  {
    id: 'kali-tsk-fls' as const,
    label: 'Sleuth Kit fls',
    description: 'The Sleuth Kit filesystem layer tool. fls lists files and directories (including deleted) from disk images; icat extracts inodes; mmls maps partition tables.',
    capabilityPacks: ['forensics', 'evidence'],
    recommendedAgents: ['code-forensics-specialist', 'evidence-reporting-specialist'],
    executionModel: 'skills-and-tools',
    netRunnerTools: ['Bash', 'TodoWrite', 'Read', 'Write'],
    requiredCommands: ['fls'],
    mitreAttackTechniques: ['T1083', 'T1070.004'],
  },
  {
    id: 'kali-yara' as const,
    label: 'YARA',
    description: 'Pattern-matching tool for malware identification. Scan extracted artifacts, memory dumps, and disk images with custom or community rule sets using yara -r rules.yar.',
    capabilityPacks: ['forensics', 'evidence', 'binary'],
    recommendedAgents: ['code-forensics-specialist', 'evidence-reporting-specialist'],
    executionModel: 'skills-and-tools',
    netRunnerTools: ['Bash', 'TodoWrite', 'Read', 'Write'],
    requiredCommands: ['yara'],
    mitreAttackTechniques: ['T1059', 'T1027', 'T1036'],
  },
  {
    id: 'kali-capa' as const,
    label: 'capa',
    description: 'Mandiant capability extraction tool that identifies what a binary does (e.g., persistence, anti-analysis, C2, data theft) by matching disassembled functions against an open rule set. Run `capa <sample>` to produce ATT&CK-mapped capability output for malware triage and binary RE.',
    capabilityPacks: ['forensics', 'binary', 'evidence'],
    recommendedAgents: ['code-forensics-specialist', 'infra-specialist', 'evidence-reporting-specialist'],
    executionModel: 'skills-and-tools',
    netRunnerTools: ['Bash', 'TodoWrite', 'Read', 'Write'],
    requiredCommands: ['capa'],
    mitreAttackTechniques: ['T1027', 'T1059', 'T1620'],
  },
]
