import type { ImportedPentestCapability } from '../types.js'

export const LATERAL_MOVEMENT_PACK_TOOLS: ImportedPentestCapability[] = [
  {
    id: "kali-bloodhound" as const,
    label: "BloodHound Collection",
    description: "Active Directory relationship graph collection capability for attack-path analysis.",
    capabilityPacks: ["lateral-movement","privilege-escalation","network","active-directory"],
    recommendedAgents: ["infra-specialist","infra-specialist","infra-specialist"],
    executionModel: "hybrid",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read","ListMcpResources","ReadMcpResource"],
    requiredCommands: ["bloodhound-python"],
    optionalMcpServers: ["active-directory","bloodhound"],
  },
  {
    id: "kali-netexec" as const,
    label: "NetExec (nxc)",
    description: "Network service exploitation framework (CrackMapExec successor) for mass credential validation and command execution across SMB/WinRM/LDAP/SSH targets.",
    capabilityPacks: ["lateral-movement","active-directory","network"],
    recommendedAgents: ["infra-specialist","infra-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["nxc"],
    mitreAttackTechniques: ["T1021.002","T1078"],
  },
  {
    id: "kali-evil-winrm" as const,
    label: "Evil-WinRM",
    description: "Full-featured WinRM shell with file upload/download and PowerShell script loading for lateral movement to Windows hosts where WinRM is enabled.",
    capabilityPacks: ["lateral-movement","active-directory"],
    recommendedAgents: ["infra-specialist","infra-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["evil-winrm"],
    mitreAttackTechniques: ["T1021.006"],
  },
  {
    id: "kali-impacket-psexec" as const,
    label: "Impacket PSExec",
    description: "SMB-based remote command execution via service creation, providing SYSTEM-level shells during lateral movement across Windows targets.",
    capabilityPacks: ["lateral-movement","active-directory","privilege-escalation"],
    recommendedAgents: ["infra-specialist","infra-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["impacket-psexec"],
    mitreAttackTechniques: ["T1021.002","T1569.002"],
  },
  {
    id: "kali-impacket-wmiexec" as const,
    label: "Impacket WMIExec",
    description: "Semi-interactive shell over WMI without dropping binaries to disk, enabling low-noise lateral execution on Windows hosts.",
    capabilityPacks: ["lateral-movement","active-directory"],
    recommendedAgents: ["infra-specialist","infra-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["impacket-wmiexec"],
    mitreAttackTechniques: ["T1047"],
  },
  {
    id: "kali-impacket-atexec" as const,
    label: "Impacket ATExec",
    description: "Remote command execution via Windows Task Scheduler (AT service) over SMB, useful for one-shot lateral execution without an interactive shell.",
    capabilityPacks: ["lateral-movement","active-directory"],
    recommendedAgents: ["infra-specialist","infra-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["impacket-atexec"],
    mitreAttackTechniques: ["T1053.005"],
  },
  {
    id: "kali-impacket-dcomexec" as const,
    label: "Impacket DCOMExec",
    description: "DCOM-based lateral execution using MMC20, ShellWindows, and ShellBrowserWindow objects to run commands on remote Windows hosts.",
    capabilityPacks: ["lateral-movement","active-directory"],
    recommendedAgents: ["infra-specialist","infra-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["impacket-dcomexec"],
    mitreAttackTechniques: ["T1021.003"],
  },
  {
    id: "kali-chisel" as const,
    label: "Chisel",
    description: "Fast TCP/UDP tunnel over HTTP with reverse-proxy support for pivoting through firewalls and reaching segmented internal networks.",
    capabilityPacks: ["lateral-movement","network"],
    recommendedAgents: ["infra-specialist","infra-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["chisel"],
    mitreAttackTechniques: ["T1572","T1090"],
  },
  {
    id: "kali-ligolo-ng" as const,
    label: "Ligolo-ng",
    description: "TUN-mode L3 pivot proxy that creates a full network interface on the operator machine, enabling transparent routing into internal subnets without SOCKS overhead.",
    capabilityPacks: ["lateral-movement","network"],
    recommendedAgents: ["infra-specialist","infra-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["ligolo-ng"],
    mitreAttackTechniques: ["T1572","T1090"],
  },
  {
    id: "kali-sshuttle" as const,
    label: "sshuttle",
    description: "VPN-over-SSH pivot that transparently routes target subnet traffic without requiring SOCKS proxychains, ideal for quick access to internal networks via a compromised SSH host.",
    capabilityPacks: ["lateral-movement","network"],
    recommendedAgents: ["infra-specialist","infra-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["sshuttle"],
    mitreAttackTechniques: ["T1572"],
  },
]
