import type { ImportedPentestCapability } from '../types.js'

export const MOBILE_PACK_TOOLS: ImportedPentestCapability[] = [
  {
    id: "kali-adb" as const,
    label: "ADB Device Bridge",
    description: "Android device bridge capability for package inspection, log capture, port forwarding, and test-device interaction.",
    capabilityPacks: ["mobile","recon","lab-control"],
    recommendedAgents: ["recon-specialist","exploit-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["adb"],
  },
  {
    id: "kali-apktool" as const,
    label: "APKTool Reverse Engineering",
    description: "Android package decoding capability for manifest review, resource extraction, and APK rebuild workflows.",
    capabilityPacks: ["mobile","binary","recon"],
    recommendedAgents: ["recon-specialist","exploit-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["apktool"],
  },
  {
    id: "kali-jadx" as const,
    label: "JADX Decompiled Review",
    description: "Android decompilation capability for source-oriented review of app logic, endpoints, and hard-coded behavior.",
    capabilityPacks: ["mobile","binary","recon"],
    recommendedAgents: ["recon-specialist","exploit-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["jadx"],
  },
  {
    id: "kali-frida" as const,
    label: "Frida Runtime Instrumentation",
    description: "Runtime instrumentation capability for live mobile app hooking, SSL pinning bypass validation, and behavior tracing.",
    capabilityPacks: ["mobile","exploitation","api"],
    recommendedAgents: ["exploit-specialist","api-testing-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["frida"],
  },
  {
    id: "kali-objection" as const,
    label: "Objection Mobile Runtime Toolkit",
    description: "Mobile runtime testing capability built on Frida for quick hooking, storage review, and instrumentation-assisted validation.",
    capabilityPacks: ["mobile","exploitation","api"],
    recommendedAgents: ["exploit-specialist","api-testing-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["objection"],
  },
  {
    id: "kali-mobsf" as const,
    label: "MobSF Mobile Analysis",
    description: "Static and dynamic mobile analysis capability for Android packages with report-oriented triage and evidence output.",
    capabilityPacks: ["mobile","binary","evidence","reporting"],
    recommendedAgents: ["recon-specialist","evidence-specialist","reporting-specialist"],
    executionModel: "hybrid",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read","ListMcpResources","ReadMcpResource"],
    requiredCommands: ["docker"],
  },
  {
    id: "kali-drozer" as const,
    label: "Drozer Android Surface Analysis",
    description: "Android component and IPC testing capability for exported activities, content providers, and intent abuse checks.",
    capabilityPacks: ["mobile","exploitation","recon"],
    recommendedAgents: ["exploit-specialist","recon-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["drozer"],
  },
  {
    id: "kali-apkleaks" as const,
    label: "APKLeaks Secret Discovery",
    description: "APK-focused secret and endpoint extraction capability for identifying hard-coded keys, hosts, and mobile-specific leaks.",
    capabilityPacks: ["mobile","recon","evidence"],
    recommendedAgents: ["recon-specialist","evidence-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["apkleaks"],
  },
]
