import type { ImportedPentestCapability } from '../types.js'

export const NETWORK_PACK_TOOLS: ImportedPentestCapability[] = [
  {
    id: "kali-masscan" as const,
    label: "Masscan High-Speed Enumeration",
    description: "High-speed port discovery capability commonly used for broad network attack-surface mapping.",
    capabilityPacks: ["network","recon"],
    recommendedAgents: ["infra-specialist","recon-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["masscan"],
  },
  {
    id: "kali-rustscan" as const,
    label: "Rustscan Enumeration",
    description: "Fast port probing capability with Nmap handoff patterns.",
    capabilityPacks: ["network","recon"],
    recommendedAgents: ["infra-specialist","recon-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["rustscan"],
  },
  {
    id: "kali-arp-scan" as const,
    label: "ARP Scan Discovery",
    description: "Layer-2 host discovery capability for local network reconnaissance.",
    capabilityPacks: ["network","recon","lab-control"],
    recommendedAgents: ["infra-specialist","recon-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["arp-scan"],
  },
  {
    id: "kali-enum4linux" as const,
    label: "Enum4linux Enumeration",
    description: "SMB/RPC Windows enumeration capability for users, shares, policies, and domain context.",
    capabilityPacks: ["network","lateral-movement","privilege-escalation"],
    recommendedAgents: ["infra-specialist","infra-specialist","infra-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["enum4linux"],
  },
  {
    id: "kali-smbmap" as const,
    label: "SMBMap Share Enumeration",
    description: "SMB share and permission mapping capability for lateral movement and data exposure checks.",
    capabilityPacks: ["network","lateral-movement","exfiltration"],
    recommendedAgents: ["infra-specialist","infra-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["smbmap"],
  },
  {
    id: "kali-netexec" as const,
    label: "NetExec SMB/AD Operations",
    description: "Credential, SMB, and AD operation capability for lateral movement and privilege testing.",
    capabilityPacks: ["network","lateral-movement","privilege-escalation","active-directory"],
    recommendedAgents: ["infra-specialist","infra-specialist","infra-specialist","infra-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["netexec"],
  },
  {
    id: "kali-responder" as const,
    label: "Responder Credential Capture",
    description: "Credential interception simulation capability for authorized internal assessment scenarios.",
    capabilityPacks: ["network","lateral-movement","exploitation"],
    recommendedAgents: ["infra-specialist","infra-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["responder"],
  },
  {
    id: "kali-medusa" as const,
    label: "Medusa Credential Auditing",
    description: "Protocol brute-force capability for credential auditing in authorized targets.",
    capabilityPacks: ["network","exploitation"],
    recommendedAgents: ["infra-specialist","infra-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["medusa"],
  },
  {
    id: "kali-patator" as const,
    label: "Patator Brute-force Framework",
    description: "Modular brute-force framework capability for protocol-specific auth testing.",
    capabilityPacks: ["network","exploitation"],
    recommendedAgents: ["infra-specialist","infra-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["patator"],
  },
  {
    id: "kali-nbtscan" as const,
    label: "NBTScan Discovery",
    description: "NetBIOS name scanner capability for Windows host discovery on local network segments.",
    capabilityPacks: ["network","active-directory","recon"],
    recommendedAgents: ["infra-specialist","infra-specialist","recon-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["nbtscan"],
  },
  {
    id: "kali-wireshark" as const,
    label: "Wireshark/TShark Analysis",
    description: "Network protocol analyser capability for deep packet capture dissection and inspection.",
    capabilityPacks: ["network","evidence","wifi"],
    recommendedAgents: ["infra-specialist","evidence-reporting-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["tshark"],
  },
  {
    id: "kali-tshark" as const,
    label: "TShark Terminal Packet Analyzer",
    description: "Terminal-based Wireshark for scriptable packet capture, protocol dissection, and field extraction.",
    capabilityPacks: ["network","evidence"],
    recommendedAgents: ["infra-specialist","evidence-reporting-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["tshark"],
  },
  {
    id: "kali-tcpdump" as const,
    label: "Tcpdump Packet Capture",
    description: "Low-level packet capture and analysis for network traffic inspection and evidence collection.",
    capabilityPacks: ["network","evidence"],
    recommendedAgents: ["infra-specialist","evidence-reporting-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["tcpdump"],
  },
]
