import type { ImportedPentestCapability } from '../types.js'

export const RECON_PACK_TOOLS: ImportedPentestCapability[] = [
  {
    id: "kali-dnsenum" as const,
    label: "DNSenum Recon",
    description: "DNS and zone reconnaissance capability for domain mapping and discovery.",
    capabilityPacks: ["recon","network"],
    recommendedAgents: ["recon-specialist","network-testing-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["dnsenum"],
  },
  {
    id: "kali-fierce" as const,
    label: "Fierce DNS Recon",
    description: "DNS brute-force and reconnaissance capability for subdomain and host discovery.",
    capabilityPacks: ["recon","network"],
    recommendedAgents: ["recon-specialist","network-testing-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["fierce"],
  },
  {
    id: "kali-theharvester" as const,
    label: "theHarvester OSINT",
    description: "OSINT and passive intel gathering capability for emails, hosts, and public records.",
    capabilityPacks: ["recon"],
    recommendedAgents: ["recon-specialist","engagement-lead"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebSearch","WebFetch","TodoWrite","Read"],
    requiredCommands: ["theHarvester"],
  },
  {
    id: "kali-gau" as const,
    label: "GAU URL Collection",
    description: "Historical URL collection capability for broader endpoint discovery.",
    capabilityPacks: ["recon","web","api"],
    recommendedAgents: ["recon-specialist","web-testing-specialist","api-testing-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebSearch","TodoWrite","Write","Read"],
    requiredCommands: ["gau"],
  },
  {
    id: "kali-waybackurls" as const,
    label: "Wayback URL Collection",
    description: "Archive-derived URL discovery capability for historical route and parameter testing.",
    capabilityPacks: ["recon","web","api"],
    recommendedAgents: ["recon-specialist","web-testing-specialist","api-testing-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebSearch","TodoWrite","Write","Read"],
    requiredCommands: ["waybackurls"],
  },
  {
    id: "kali-uro" as const,
    label: "URO URL Reduction",
    description: "URL deduplication and normalization capability for high-volume recon workflows.",
    capabilityPacks: ["recon","web","api"],
    recommendedAgents: ["recon-specialist","engagement-lead"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["uro"],
  },
  {
    id: "kali-sherlock" as const,
    label: "Sherlock Username OSINT",
    description: "Username investigation capability across 400+ social networks for identity correlation.",
    capabilityPacks: ["recon"],
    recommendedAgents: ["recon-specialist","engagement-lead"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebSearch","TodoWrite","Write","Read"],
    requiredCommands: ["sherlock"],
  },
  {
    id: "kali-recon-ng" as const,
    label: "Recon-ng Framework",
    description: "Modular web reconnaissance framework capability for OSINT data gathering and correlation.",
    capabilityPacks: ["recon","network"],
    recommendedAgents: ["recon-specialist","engagement-lead"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebSearch","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["recon-ng"],
  },
  {
    id: "kali-spiderfoot" as const,
    label: "SpiderFoot OSINT Automation",
    description: "OSINT automation capability with 200+ data-gathering modules for target profiling.",
    capabilityPacks: ["recon"],
    recommendedAgents: ["recon-specialist","engagement-lead"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebSearch","TodoWrite","Write","Read"],
    requiredCommands: ["spiderfoot"],
  },
  {
    id: "kali-bbot" as const,
    label: "BBOT Reconnaissance",
    description: "Recursive OSINT and attack surface mapping capability with modular scan architecture.",
    capabilityPacks: ["recon","web","network"],
    recommendedAgents: ["recon-specialist","web-testing-specialist","engagement-lead"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["bbot"],
  },
  {
    id: "kali-whois" as const,
    label: "WHOIS Lookup",
    description: "Domain and IP registration lookup capability for ownership and infrastructure intelligence.",
    capabilityPacks: ["recon","network"],
    recommendedAgents: ["recon-specialist","network-testing-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["whois"],
  },
  {
    id: "kali-sublist3r" as const,
    label: "Sublist3r Enumeration",
    description: "Subdomain enumeration capability using multiple OSINT sources for domain surface mapping.",
    capabilityPacks: ["recon","network"],
    recommendedAgents: ["recon-specialist","network-testing-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["sublist3r"],
  },
  {
    id: "kali-ghunt" as const,
    label: "GHunt Google OSINT",
    description: "Google account OSINT capability for account-linked service discovery and Google-exposed profiling data.",
    capabilityPacks: ["recon"],
    recommendedAgents: ["recon-specialist","engagement-lead"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebSearch","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["ghunt"],
  },
  {
    id: "kali-holehe" as const,
    label: "Holehe Email Enumeration",
    description: "Email-to-account mapping capability across public services for identity correlation and target profiling.",
    capabilityPacks: ["recon"],
    recommendedAgents: ["recon-specialist","engagement-lead"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebSearch","TodoWrite","Write","Read"],
    requiredCommands: ["holehe"],
  },
  {
    id: "kali-haklistgen" as const,
    label: "Haklistgen Custom Wordlists",
    description: "Target-derived wordlist generation capability for stronger fuzzing and content-discovery coverage.",
    capabilityPacks: ["recon","web","api"],
    recommendedAgents: ["recon-specialist","web-testing-specialist","api-testing-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebSearch","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["haklistgen"],
  },
  {
    id: "kali-autorecon" as const,
    label: "AutoRecon Multi-Tool Recon",
    description: "Automated multi-tool reconnaissance capability for parallel nmap, web, and service scanning.",
    capabilityPacks: ["recon","network","web"],
    recommendedAgents: ["recon-specialist","network-testing-specialist","engagement-lead"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["autorecon"],
  },
  {
    id: "kali-nmap" as const,
    label: "Nmap Port Scanner",
    description: "Network port scanning and service detection with NSE scripting, OS fingerprinting, and version enumeration.",
    capabilityPacks: ["recon","network"],
    recommendedAgents: ["recon-specialist","network-testing-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["nmap"],
  },
  {
    id: "kali-amass" as const,
    label: "Amass Subdomain Enumeration",
    description: "In-depth attack surface mapping and subdomain enumeration via DNS, scraping, and certificate transparency.",
    capabilityPacks: ["recon"],
    recommendedAgents: ["recon-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["amass"],
  },
  {
    id: "kali-subfinder" as const,
    label: "Subfinder Passive Subdomain Discovery",
    description: "Fast passive subdomain discovery using multiple sources including certificate transparency, DNS datasets, and APIs.",
    capabilityPacks: ["recon"],
    recommendedAgents: ["recon-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["subfinder"],
  },
  {
    id: "kali-whatweb" as const,
    label: "WhatWeb Technology Fingerprinting",
    description: "Web technology fingerprinting identifying CMS, frameworks, web servers, JavaScript libraries, and embedded devices.",
    capabilityPacks: ["recon","web"],
    recommendedAgents: ["recon-specialist","web-testing-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["whatweb"],
  },
  {
    id: "kali-maltego" as const,
    label: "Maltego OSINT Link Analysis",
    description: "Interactive data mining and link analysis tool for OSINT investigations mapping relationships between entities.",
    capabilityPacks: ["recon"],
    recommendedAgents: ["recon-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["maltego"],
  },
  {
    id: "kali-parsero" as const,
    label: "Parsero Robots.txt Analyzer",
    description: "Parse robots.txt Disallow entries to discover hidden paths and potentially sensitive directories.",
    capabilityPacks: ["recon","web"],
    recommendedAgents: ["recon-specialist","web-testing-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["parsero"],
  },
  {
    id: "kali-subzy" as const,
    label: "Subzy Subdomain Takeover",
    description: "Subdomain takeover detection capability covering modern fingerprints across SaaS providers for fast hijack-risk validation.",
    capabilityPacks: ["recon","web","exploitation"],
    recommendedAgents: ["recon-specialist","web-testing-specialist","exploit-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["subzy"],
  },
  {
    id: "kali-subjack" as const,
    label: "Subjack Subdomain Takeover",
    description: "Classic subdomain takeover scanning capability for unverified vendor configurations across web targets.",
    capabilityPacks: ["recon","web","exploitation"],
    recommendedAgents: ["recon-specialist","web-testing-specialist","exploit-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["subjack"],
  },
  {
    id: "kali-getjs" as const,
    label: "GetJS JavaScript Harvesting",
    description: "JavaScript URL extraction capability for downstream secret mining and endpoint discovery.",
    capabilityPacks: ["recon","web","api"],
    recommendedAgents: ["recon-specialist","web-testing-specialist","api-testing-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["getJS"],
  },
  {
    id: "kali-subjs" as const,
    label: "Subjs JavaScript Discovery",
    description: "Fast subdomain-driven JavaScript URL discovery capability for SPA endpoint and secret mining.",
    capabilityPacks: ["recon","web","api"],
    recommendedAgents: ["recon-specialist","web-testing-specialist","api-testing-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["subjs"],
  },
  {
    id: "kali-linkfinder" as const,
    label: "LinkFinder JS Endpoint Mining",
    description: "Static JavaScript endpoint and route discovery capability for SPA attack-surface expansion.",
    capabilityPacks: ["recon","web","api"],
    recommendedAgents: ["recon-specialist","web-testing-specialist","api-testing-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["linkfinder"],
  },
  {
    id: "kali-secretfinder" as const,
    label: "SecretFinder JS Secret Discovery",
    description: "JavaScript secret-pattern scanning capability for API keys, tokens, and credentials embedded in client code.",
    capabilityPacks: ["recon","web","api","evidence"],
    recommendedAgents: ["recon-specialist","web-testing-specialist","api-testing-specialist","evidence-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["secretfinder"],
  },
  {
    id: "kali-mantra" as const,
    label: "Mantra JS Token Mining",
    description: "JavaScript file token-mining capability for streamlined client-side credential and key discovery.",
    capabilityPacks: ["recon","web","api","evidence"],
    recommendedAgents: ["recon-specialist","web-testing-specialist","api-testing-specialist","evidence-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["mantra"],
  },
  {
    id: "kali-trufflehog" as const,
    label: "Trufflehog Secret Scanning",
    description: "Secret scanning capability for source repositories, filesystems, and remote sources with high-signal verifier set.",
    capabilityPacks: ["recon","web","evidence","reporting"],
    recommendedAgents: ["recon-specialist","web-testing-specialist","evidence-specialist","reporting-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["trufflehog"],
  },
  {
    id: "kali-gf" as const,
    label: "GF Pattern Matching",
    description: "Tomnomnom gf pattern-matching capability for triaging URL/parameter lists into vulnerability-class candidate buckets.",
    capabilityPacks: ["recon","web","api"],
    recommendedAgents: ["recon-specialist","web-testing-specialist","api-testing-specialist","exploit-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["gf"],
  },
  {
    id: "kali-kxss" as const,
    label: "Kxss Reflected Parameter Detection",
    description: "Reflected-parameter detection capability for fast XSS-candidate triage feeding dalfox and headless browser validation.",
    capabilityPacks: ["recon","web","api","exploitation"],
    recommendedAgents: ["recon-specialist","web-testing-specialist","api-testing-specialist","exploit-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["kxss"],
  },
  {
    id: "kali-interactsh-client" as const,
    label: "Interactsh Client OOB Validation",
    description: "Project Discovery interactsh-client capability for OOB validation of blind SSRF, blind XSS, blind RCE, and JNDI/log4shell payloads.",
    capabilityPacks: ["recon","web","api","exploitation","evidence"],
    recommendedAgents: ["recon-specialist","web-testing-specialist","api-testing-specialist","exploit-specialist","evidence-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["interactsh-client"],
  },
  {
    id: "kali-smuggler" as const,
    label: "Smuggler HTTP Request Smuggling",
    description: "HTTP request smuggling probing capability for CL.TE/TE.CL/TE.TE detection on authorized targets.",
    capabilityPacks: ["recon","web","api","exploitation"],
    recommendedAgents: ["recon-specialist","web-testing-specialist","api-testing-specialist","exploit-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["smuggler"],
  },
]
