import type { ImportedPentestCapability } from '../types.js'

export const RECON_PACK_TOOLS: ImportedPentestCapability[] = [
  {
    id: "kali-dnsenum" as const,
    label: "DNSenum Recon",
    description: "DNS and zone reconnaissance capability for domain mapping and discovery.",
    capabilityPacks: ["recon","network"],
    recommendedAgents: ["recon-specialist","network-testing-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["dnsenum"],
  },
  {
    id: "kali-fierce" as const,
    label: "Fierce DNS Recon",
    description: "DNS brute-force and reconnaissance capability for subdomain and host discovery.",
    capabilityPacks: ["recon","network"],
    recommendedAgents: ["recon-specialist","network-testing-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["fierce"],
  },
  {
    id: "kali-theharvester" as const,
    label: "theHarvester OSINT",
    description: "OSINT and passive intel gathering capability for emails, hosts, and public records.",
    capabilityPacks: ["recon"],
    recommendedAgents: ["recon-specialist","engagement-lead"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebSearch","WebFetch","TodoWrite","Read"],
    requiredCommands: ["theHarvester"],
  },
  {
    id: "kali-gau" as const,
    label: "GAU URL Collection",
    description: "Historical URL collection capability for broader endpoint discovery.",
    capabilityPacks: ["recon","web","api"],
    recommendedAgents: ["recon-specialist","web-testing-specialist","api-testing-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebSearch","TodoWrite","Write","Read"],
    requiredCommands: ["gau"],
  },
  {
    id: "kali-waybackurls" as const,
    label: "Wayback URL Collection",
    description: "Archive-derived URL discovery capability for historical route and parameter testing.",
    capabilityPacks: ["recon","web","api"],
    recommendedAgents: ["recon-specialist","web-testing-specialist","api-testing-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebSearch","TodoWrite","Write","Read"],
    requiredCommands: ["waybackurls"],
  },
  {
    id: "kali-uro" as const,
    label: "URO URL Reduction",
    description: "URL deduplication and normalization capability for high-volume recon workflows.",
    capabilityPacks: ["recon","web","api"],
    recommendedAgents: ["recon-specialist","engagement-lead"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["uro"],
  },
  {
    id: "kali-sherlock" as const,
    label: "Sherlock Username OSINT",
    description: "Username investigation capability across 400+ social networks for identity correlation.",
    capabilityPacks: ["recon"],
    recommendedAgents: ["recon-specialist","engagement-lead"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebSearch","TodoWrite","Write","Read"],
    requiredCommands: ["sherlock"],
  },
  {
    id: "kali-recon-ng" as const,
    label: "Recon-ng Framework",
    description: "Modular web reconnaissance framework capability for OSINT data gathering and correlation.",
    capabilityPacks: ["recon","network"],
    recommendedAgents: ["recon-specialist","engagement-lead"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebSearch","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["recon-ng"],
  },
  {
    id: "kali-spiderfoot" as const,
    label: "SpiderFoot OSINT Automation",
    description: "OSINT automation capability with 200+ data-gathering modules for target profiling.",
    capabilityPacks: ["recon"],
    recommendedAgents: ["recon-specialist","engagement-lead"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebSearch","TodoWrite","Write","Read"],
    requiredCommands: ["spiderfoot"],
  },
  {
    id: "kali-bbot" as const,
    label: "BBOT Reconnaissance",
    description: "Recursive OSINT and attack surface mapping capability with modular scan architecture.",
    capabilityPacks: ["recon","web","network"],
    recommendedAgents: ["recon-specialist","web-testing-specialist","engagement-lead"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["bbot"],
  },
  {
    id: "kali-whois" as const,
    label: "WHOIS Lookup",
    description: "Domain and IP registration lookup capability for ownership and infrastructure intelligence.",
    capabilityPacks: ["recon","network"],
    recommendedAgents: ["recon-specialist","network-testing-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["whois"],
  },
  {
    id: "kali-sublist3r" as const,
    label: "Sublist3r Enumeration",
    description: "Subdomain enumeration capability using multiple OSINT sources for domain surface mapping.",
    capabilityPacks: ["recon","network"],
    recommendedAgents: ["recon-specialist","network-testing-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["sublist3r"],
  },
  {
    id: "kali-ghunt" as const,
    label: "GHunt Google OSINT",
    description: "Google account OSINT capability for account-linked service discovery and Google-exposed profiling data.",
    capabilityPacks: ["recon"],
    recommendedAgents: ["recon-specialist","engagement-lead"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebSearch","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["ghunt"],
  },
  {
    id: "kali-holehe" as const,
    label: "Holehe Email Enumeration",
    description: "Email-to-account mapping capability across public services for identity correlation and target profiling.",
    capabilityPacks: ["recon"],
    recommendedAgents: ["recon-specialist","engagement-lead"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebSearch","TodoWrite","Write","Read"],
    requiredCommands: ["holehe"],
  },
  {
    id: "kali-haklistgen" as const,
    label: "Haklistgen Custom Wordlists",
    description: "Target-derived wordlist generation capability for stronger fuzzing and content-discovery coverage.",
    capabilityPacks: ["recon","web","api"],
    recommendedAgents: ["recon-specialist","web-testing-specialist","api-testing-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebSearch","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["haklistgen"],
  },
  {
    id: "kali-autorecon" as const,
    label: "AutoRecon Multi-Tool Recon",
    description: "Automated multi-tool reconnaissance capability for parallel nmap, web, and service scanning.",
    capabilityPacks: ["recon","network","web"],
    recommendedAgents: ["recon-specialist","network-testing-specialist","engagement-lead"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["autorecon"],
  },
  {
    id: "kali-nmap" as const,
    label: "Nmap Port Scanner",
    description: "Network port scanning and service detection with NSE scripting, OS fingerprinting, and version enumeration.",
    capabilityPacks: ["recon","network"],
    recommendedAgents: ["recon-specialist","network-testing-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["nmap"],
  },
  {
    id: "kali-amass" as const,
    label: "Amass Subdomain Enumeration",
    description: "In-depth attack surface mapping and subdomain enumeration via DNS, scraping, and certificate transparency.",
    capabilityPacks: ["recon"],
    recommendedAgents: ["recon-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["amass"],
  },
  {
    id: "kali-subfinder" as const,
    label: "Subfinder Passive Subdomain Discovery",
    description: "Fast passive subdomain discovery using multiple sources including certificate transparency, DNS datasets, and APIs.",
    capabilityPacks: ["recon"],
    recommendedAgents: ["recon-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["subfinder"],
  },
  {
    id: "kali-whatweb" as const,
    label: "WhatWeb Technology Fingerprinting",
    description: "Web technology fingerprinting identifying CMS, frameworks, web servers, JavaScript libraries, and embedded devices.",
    capabilityPacks: ["recon","web"],
    recommendedAgents: ["recon-specialist","web-testing-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["whatweb"],
  },
  {
    id: "kali-maltego" as const,
    label: "Maltego OSINT Link Analysis",
    description: "Interactive data mining and link analysis tool for OSINT investigations mapping relationships between entities.",
    capabilityPacks: ["recon"],
    recommendedAgents: ["recon-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["maltego"],
  },
  {
    id: "kali-parsero" as const,
    label: "Parsero Robots.txt Analyzer",
    description: "Parse robots.txt Disallow entries to discover hidden paths and potentially sensitive directories.",
    capabilityPacks: ["recon","web"],
    recommendedAgents: ["recon-specialist","web-testing-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["parsero"],
  },
]
