import type { ImportedPentestCapability } from '../types.js'

export const THREAT_INTEL_PACK_TOOLS: ImportedPentestCapability[] = [
  {
    id: 'kali-greynoise' as const,
    label: 'GreyNoise CLI',
    description: 'IP reputation and context lookup against GreyNoise mass-scan intelligence. Run `greynoise ip <ip>` (binary: greynoise) or query via `curl -H "key: $GREYNOISE_API_KEY" https://api.greynoise.io/v3/community/<ip>` for community tier. Classifies IPs as benign scanners, malicious, or unknown.',
    capabilityPacks: ['threat-intel', 'recon'],
    recommendedAgents: ['recon-specialist', 'engagement-lead', 'web-testing-specialist', 'forensics-specialist'],
    executionModel: 'skills-and-tools',
    netRunnerTools: ['Bash', 'WebFetch', 'Read', 'Write', 'TodoWrite'],
    requiredCommands: ['greynoise'],
    mitreAttackTechniques: ['T1590', 'T1596'],
  },
  {
    id: 'kali-vt-cli' as const,
    label: 'VirusTotal CLI (vt)',
    description: 'Official VirusTotal v3 CLI for IP, domain, file hash, and URL reputation lookups. Run `vt ip <ip>`, `vt domain <domain>`, `vt file <sha256>`, or `vt url <url>` (binary: vt; requires VT_API_KEY). Free tier: 4 requests/minute, 500/day — add inter-call delay for bulk enrichment.',
    capabilityPacks: ['threat-intel', 'recon'],
    recommendedAgents: ['recon-specialist', 'engagement-lead', 'web-testing-specialist', 'forensics-specialist'],
    executionModel: 'skills-and-tools',
    netRunnerTools: ['Bash', 'WebFetch', 'Read', 'Write', 'TodoWrite'],
    requiredCommands: ['vt'],
    mitreAttackTechniques: ['T1589', 'T1590', 'T1596'],
  },
  {
    id: 'kali-urlscan' as const,
    label: 'urlscan CLI',
    description: 'Submit URLs to urlscan.io for sandboxed browser rendering and screenshot capture. Run `urlscan submit <url>` (binary: urlscan; requires URLSCAN_API_KEY) or via curl POST to `https://urlscan.io/api/v1/scan/`. Retrieve results after ~10 s via `https://urlscan.io/api/v1/result/<uuid>/`. Use `visibility: private` for sensitive targets.',
    capabilityPacks: ['threat-intel', 'recon'],
    recommendedAgents: ['recon-specialist', 'engagement-lead', 'web-testing-specialist'],
    executionModel: 'skills-and-tools',
    netRunnerTools: ['Bash', 'WebFetch', 'Read', 'Write', 'TodoWrite'],
    requiredCommands: ['urlscan'],
    mitreAttackTechniques: ['T1596', 'T1590'],
  },
  {
    id: 'kali-mihari' as const,
    label: 'Mihari',
    description: 'Rule-based threat hunting and IOC pivot framework. Run `mihari search <query>` and `mihari artifacts <rule-id>` (binary: mihari) to discover infrastructure sharing the same cert fingerprint, ASN, favicon hash, or response pattern as known-malicious indicators. Integrates with Shodan, Censys, GreyNoise, VirusTotal, and Fofa.',
    capabilityPacks: ['threat-intel', 'recon'],
    recommendedAgents: ['recon-specialist', 'engagement-lead'],
    executionModel: 'skills-and-tools',
    netRunnerTools: ['Bash', 'WebFetch', 'Read', 'Write', 'TodoWrite'],
    requiredCommands: ['mihari'],
    mitreAttackTechniques: ['T1596', 'T1590', 'T1589'],
  },
  {
    id: 'kali-shodan-cli' as const,
    label: 'Shodan CLI',
    description: 'Internet-wide banner and service intelligence via Shodan API. Run `shodan host <ip>` for per-host detail and `shodan search <query>` for bulk queries (binary: shodan; requires SHODAN_API_KEY). Pivot on SSL cert subjects, favicon hashes, HTTP banners, and open ports to map attacker infrastructure.',
    capabilityPacks: ['threat-intel', 'recon'],
    recommendedAgents: ['recon-specialist', 'engagement-lead', 'web-testing-specialist'],
    executionModel: 'skills-and-tools',
    netRunnerTools: ['Bash', 'WebFetch', 'Read', 'Write', 'TodoWrite'],
    requiredCommands: ['shodan'],
    mitreAttackTechniques: ['T1590', 'T1596'],
  },
  {
    id: 'kali-censys' as const,
    label: 'Censys CLI',
    description: 'Certificate and host intelligence from Censys. Run `censys search "<query>" --index-type hosts` or `censys search "<domain>" --index-type certificates` (binary: censys; requires CENSYS_API_ID and CENSYS_API_SECRET). Use for passive DNS correlation, cert pivoting, and infrastructure attribution.',
    capabilityPacks: ['threat-intel', 'recon'],
    recommendedAgents: ['recon-specialist', 'engagement-lead', 'web-testing-specialist'],
    executionModel: 'skills-and-tools',
    netRunnerTools: ['Bash', 'WebFetch', 'Read', 'Write', 'TodoWrite'],
    requiredCommands: ['censys'],
    mitreAttackTechniques: ['T1590', 'T1596'],
  },
  {
    id: 'kali-misp-cli' as const,
    label: 'MISP (pymisp)',
    description: 'MISP threat intelligence platform client via pymisp Python library — no standalone CLI binary exists; use `python` with pymisp to search events, attributes, and galaxy clusters by IOC value or type. Requires MISP_URL and MISP_KEY env vars. Example: `python -c "from pymisp import PyMISP; ..."`. Results include event IDs, tags, sharing groups, and ATT&CK galaxy mappings.',
    capabilityPacks: ['threat-intel', 'recon'],
    recommendedAgents: ['recon-specialist', 'engagement-lead', 'forensics-specialist'],
    executionModel: 'skills-and-tools',
    netRunnerTools: ['Bash', 'WebFetch', 'Read', 'Write', 'TodoWrite'],
    requiredCommands: ['python'],
    mitreAttackTechniques: ['T1589', 'T1590', 'T1596'],
  },
  {
    id: 'kali-opencti-cli' as const,
    label: 'OpenCTI (pycti)',
    description: 'OpenCTI threat intelligence platform client via pycti Python library — no standalone CLI binary exists; use `python` with pycti to query STIX cyber observables, threat actors, campaigns, and TTPs. Requires OPENCTI_URL and OPENCTI_TOKEN env vars. Example: `python -c "from pycti import OpenCTIApiClient; ..."`. Maps observables to threat actors, intrusion sets, and MITRE ATT&CK patterns.',
    capabilityPacks: ['threat-intel', 'recon'],
    recommendedAgents: ['recon-specialist', 'engagement-lead', 'forensics-specialist'],
    executionModel: 'skills-and-tools',
    netRunnerTools: ['Bash', 'WebFetch', 'Read', 'Write', 'TodoWrite'],
    requiredCommands: ['python'],
    mitreAttackTechniques: ['T1589', 'T1590', 'T1596'],
  },
]
