import type { ImportedPentestCapability } from '../types.js'

export const WEB_PACK_TOOLS: ImportedPentestCapability[] = [
  {
    id: "kali-httpx" as const,
    label: "HTTPX Probing",
    description: "HTTP probing and service fingerprinting capability across host and URL lists.",
    capabilityPacks: ["web","api","recon"],
    recommendedAgents: ["web-testing-specialist","api-testing-specialist","recon-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["httpx"],
  },
  {
    id: "kali-katana" as const,
    label: "Katana Crawling",
    description: "Modern web crawling capability for endpoint extraction and route surface expansion.",
    capabilityPacks: ["web","api","recon"],
    recommendedAgents: ["web-testing-specialist","api-testing-specialist","recon-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["katana"],
  },
  {
    id: "kali-feroxbuster" as const,
    label: "Feroxbuster Content Discovery",
    description: "Recursive content discovery capability for web routes and hidden paths.",
    capabilityPacks: ["web","api","recon"],
    recommendedAgents: ["web-testing-specialist","api-testing-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["feroxbuster"],
  },
  {
    id: "kali-dirsearch" as const,
    label: "Dirsearch Discovery",
    description: "Directory and file brute-force capability for endpoint and asset discovery.",
    capabilityPacks: ["web","api","recon"],
    recommendedAgents: ["web-testing-specialist","api-testing-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["dirsearch"],
  },
  {
    id: "kali-wafw00f" as const,
    label: "WAF Detection",
    description: "Web application firewall fingerprinting capability for evasion-aware testing plans.",
    capabilityPacks: ["web","api","recon"],
    recommendedAgents: ["web-testing-specialist","api-testing-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["wafw00f"],
  },
  {
    id: "kali-wpscan" as const,
    label: "WPScan Assessment",
    description: "WordPress-focused vulnerability and misconfiguration assessment capability.",
    capabilityPacks: ["web","exploitation","reporting"],
    recommendedAgents: ["web-testing-specialist","exploit-specialist","retest-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["wpscan"],
  },
  {
    id: "kali-dalfox" as const,
    label: "Dalfox XSS Testing",
    description: "XSS-focused testing capability for reflected and stored input vector validation.",
    capabilityPacks: ["web","api","exploitation"],
    recommendedAgents: ["web-testing-specialist","exploit-specialist","retest-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["dalfox"],
  },
  {
    id: "kali-jaeles" as const,
    label: "Jaeles Signature Scanning",
    description: "Signature-based web vulnerability scanning capability for templated checks.",
    capabilityPacks: ["web","api","exploitation"],
    recommendedAgents: ["web-testing-specialist","api-testing-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["jaeles"],
  },
  {
    id: "kali-zap" as const,
    label: "OWASP ZAP Automation",
    description: "Active and passive web scanning capability through OWASP ZAP workflows.",
    capabilityPacks: ["web","api","exploitation","lab-control"],
    recommendedAgents: ["web-testing-specialist","api-testing-specialist","exploit-specialist"],
    executionModel: "hybrid",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read","ListMcpResources","ReadMcpResource"],
    requiredCommands: ["zap-cli"],
    optionalMcpServers: ["zap"],
  },
  {
    id: "kali-burpsuite" as const,
    label: "Burp Suite Integration",
    description: "Proxy and web testing integration capability via Burp Suite workflows.",
    capabilityPacks: ["web","api","lab-control"],
    recommendedAgents: ["web-testing-specialist","api-testing-specialist","exploit-specialist"],
    executionModel: "hybrid",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read","ListMcpResources","ReadMcpResource"],
    requiredCommands: ["burpsuite"],
    optionalMcpServers: ["burp"],
  },
  {
    id: "kali-arjun" as const,
    label: "Arjun Parameter Discovery",
    description: "HTTP parameter discovery capability for hidden input vector mapping.",
    capabilityPacks: ["web","api","recon"],
    recommendedAgents: ["web-testing-specialist","api-testing-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["arjun"],
  },
  {
    id: "kali-paramspider" as const,
    label: "ParamSpider Discovery",
    description: "URL parameter harvesting capability for fuzzing and injection preparation.",
    capabilityPacks: ["web","api","recon"],
    recommendedAgents: ["web-testing-specialist","api-testing-specialist","recon-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["paramspider"],
  },
  {
    id: "kali-x8" as const,
    label: "x8 Parameter Discovery",
    description: "Fast hidden-parameter discovery capability to expand API and web testing coverage.",
    capabilityPacks: ["web","api","recon"],
    recommendedAgents: ["api-testing-specialist","web-testing-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["x8"],
  },
  {
    id: "kali-qsreplace" as const,
    label: "QSReplace Query Mutation",
    description: "Query-string mutation capability for parameter fuzzing and reflected input checks.",
    capabilityPacks: ["web","api","exploitation"],
    recommendedAgents: ["api-testing-specialist","web-testing-specialist","exploit-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["qsreplace"],
  },
  {
    id: "kali-commix" as const,
    label: "Commix Command Injection",
    description: "Automated command injection detection and exploitation capability for web applications.",
    capabilityPacks: ["web","exploitation"],
    recommendedAgents: ["web-testing-specialist","exploit-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["commix"],
  },
  {
    id: "kali-xsser" as const,
    label: "XSSer Testing",
    description: "Cross-site scripting detection and exploitation capability for reflected and stored XSS vectors.",
    capabilityPacks: ["web","exploitation"],
    recommendedAgents: ["web-testing-specialist","exploit-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["xsser"],
  },
  {
    id: "kali-dotdotpwn" as const,
    label: "DotDotPwn Traversal",
    description: "Directory traversal fuzzing capability for path traversal vulnerability detection.",
    capabilityPacks: ["web","exploitation"],
    recommendedAgents: ["web-testing-specialist","exploit-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["dotdotpwn"],
  },
  {
    id: "kali-wfuzz" as const,
    label: "WFuzz Web Fuzzer",
    description: "Web application fuzzer capability for directory, parameter, and authentication testing.",
    capabilityPacks: ["web","api","recon"],
    recommendedAgents: ["web-testing-specialist","api-testing-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["wfuzz"],
  },
  {
    id: "kali-hakrawler" as const,
    label: "Hakrawler Web Crawler",
    description: "Fast web crawler capability for link, form, and endpoint extraction with depth control.",
    capabilityPacks: ["web","api","recon"],
    recommendedAgents: ["web-testing-specialist","recon-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["hakrawler"],
  },
  {
    id: "kali-joomscan" as const,
    label: "JoomScan Assessment",
    description: "Joomla CMS vulnerability scanning capability for component and version detection.",
    capabilityPacks: ["web","exploitation","recon"],
    recommendedAgents: ["web-testing-specialist","exploit-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["joomscan"],
  },
  {
    id: "kali-dirb" as const,
    label: "DIRB Content Scanner",
    description: "Classic web content scanner capability using wordlist-based URL enumeration.",
    capabilityPacks: ["web","recon"],
    recommendedAgents: ["web-testing-specialist","recon-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["dirb"],
  },
  {
    id: "kali-testssl" as const,
    label: "TestSSL TLS Analysis",
    description: "TLS/SSL configuration analysis capability for cipher, protocol, and certificate validation.",
    capabilityPacks: ["web","network","recon"],
    recommendedAgents: ["web-testing-specialist","network-testing-specialist","recon-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["testssl"],
  },
  {
    id: "kali-sslyze" as const,
    label: "SSLyze TLS Scanner",
    description: "Fast TLS/SSL server scanning capability for compliance and vulnerability checks.",
    capabilityPacks: ["web","network","recon"],
    recommendedAgents: ["web-testing-specialist","network-testing-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["sslyze"],
  },
  {
    id: "kali-nikto" as const,
    label: "Nikto Web Server Scanner",
    description: "Web server vulnerability scanner checking for dangerous files, outdated software, and misconfigurations.",
    capabilityPacks: ["web","recon"],
    recommendedAgents: ["web-testing-specialist","recon-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["nikto"],
  },
  {
    id: "kali-nuclei" as const,
    label: "Nuclei Template Scanner",
    description: "Template-based vulnerability scanner with community-driven detection templates for CVEs, misconfigs, and exposures.",
    capabilityPacks: ["web","recon","exploitation"],
    recommendedAgents: ["web-testing-specialist","recon-specialist","exploit-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["nuclei"],
  },
  {
    id: "kali-sqlmap" as const,
    label: "SQLMap SQL Injection",
    description: "Automatic SQL injection detection and exploitation tool supporting all major database backends.",
    capabilityPacks: ["web","exploitation","database"],
    recommendedAgents: ["web-testing-specialist","exploit-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["sqlmap"],
  },
  {
    id: "kali-gobuster" as const,
    label: "Gobuster Directory Brute-Forcer",
    description: "Fast directory and file brute-forcer for web servers, DNS subdomains, and virtual hosts.",
    capabilityPacks: ["web","recon"],
    recommendedAgents: ["web-testing-specialist","recon-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["gobuster"],
  },
  {
    id: "kali-ffuf" as const,
    label: "FFUF Web Fuzzer",
    description: "Fast web fuzzer for directory discovery, vhost enumeration, and parameter fuzzing with advanced filtering.",
    capabilityPacks: ["web","recon","api"],
    recommendedAgents: ["web-testing-specialist","recon-specialist","api-testing-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","WebFetch","TodoWrite","Write","Read"],
    requiredCommands: ["ffuf"],
  },
]
