import type { ImportedPentestCapability } from '../types.js'

export const WIFI_PACK_TOOLS: ImportedPentestCapability[] = [
  {
    id: "kali-aircrack-ng" as const,
    label: "Aircrack-ng Suite",
    description: "WPA/WPA2 PSK cracking capability from captured handshake files using wordlist attacks.",
    capabilityPacks: ["wifi","exploitation"],
    recommendedAgents: ["network-testing-specialist","exploit-specialist","wifi-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["aircrack-ng"],
  },
  {
    id: "kali-airmon-ng" as const,
    label: "Airmon-ng Monitor Mode",
    description: "Wireless interface monitor mode management capability for packet capture preparation.",
    capabilityPacks: ["wifi","recon"],
    recommendedAgents: ["network-testing-specialist","recon-specialist","wifi-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["airmon-ng"],
  },
  {
    id: "kali-airodump-ng" as const,
    label: "Airodump-ng Capture",
    description: "Passive 802.11 capture capability for AP/client discovery and WPA handshake collection.",
    capabilityPacks: ["wifi","recon"],
    recommendedAgents: ["network-testing-specialist","recon-specialist","wifi-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["airodump-ng"],
  },
  {
    id: "kali-aireplay-ng" as const,
    label: "Aireplay-ng Injection",
    description: "Packet injection capability for deauth, fake auth, ARP replay, and injection testing.",
    capabilityPacks: ["wifi","exploitation"],
    recommendedAgents: ["network-testing-specialist","exploit-specialist","wifi-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["aireplay-ng"],
  },
  {
    id: "kali-bettercap" as const,
    label: "Bettercap MITM Framework",
    description: "Advanced network attack framework capability for MITM, sniffing, spoofing, and WiFi attacks.",
    capabilityPacks: ["wifi","network","exploitation"],
    recommendedAgents: ["network-testing-specialist","exploit-specialist","wifi-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["bettercap"],
  },
  {
    id: "kali-wifite" as const,
    label: "Wifite Automated WiFi",
    description: "Automated wireless attack capability for WEP/WPA/WPA2 network testing workflows.",
    capabilityPacks: ["wifi","exploitation"],
    recommendedAgents: ["network-testing-specialist","exploit-specialist","wifi-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["wifite"],
  },
  {
    id: "kali-eaphammer" as const,
    label: "EAPHammer Evil Twin",
    description: "Rogue access point capability for WPA-Enterprise evil twin and credential capture attacks.",
    capabilityPacks: ["wifi","exploitation","network"],
    recommendedAgents: ["network-testing-specialist","exploit-specialist","wifi-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["eaphammer"],
  },
  {
    id: "kali-hcxdumptool" as const,
    label: "Hcxdumptool Capture",
    description: "Raw 802.11 frame capture capability for PMKID and handshake collection.",
    capabilityPacks: ["wifi","recon"],
    recommendedAgents: ["network-testing-specialist","recon-specialist","wifi-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["hcxdumptool"],
  },
  {
    id: "kali-kismet" as const,
    label: "Kismet Wireless IDS",
    description: "Wireless network detector, sniffer, and intrusion detection capability.",
    capabilityPacks: ["wifi","recon","network"],
    recommendedAgents: ["network-testing-specialist","recon-specialist","wifi-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["kismet"],
  },
  {
    id: "kali-mdk4" as const,
    label: "MDK4 WiFi Attack Tool",
    description: "WiFi DoS and attack tool for deauthentication, fake authentication, beacon flooding, and SSID probing.",
    capabilityPacks: ["wifi"],
    recommendedAgents: ["network-testing-specialist","wifi-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["mdk4"],
  },
  {
    id: "kali-hcxpcapngtool" as const,
    label: "HcxPcapngTool Capture Converter",
    description: "Convert and filter 802.11 capture files between formats for offline cracking and analysis workflows.",
    capabilityPacks: ["wifi"],
    recommendedAgents: ["network-testing-specialist","wifi-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["hcxpcapngtool"],
  },
  {
    id: "kali-airbase-ng" as const,
    label: "Airbase-ng Rogue Access Point",
    description: "Rogue access point framework for WiFi attacks including evil twin, karma, and client-side exploitation.",
    capabilityPacks: ["wifi","exploitation"],
    recommendedAgents: ["network-testing-specialist","exploit-specialist","wifi-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["airbase-ng"],
  },
  {
    id: "kali-airdecap-ng" as const,
    label: "Airdecap-ng WiFi Decryption",
    description: "Decrypt WEP/WPA/WPA2 capture files with known keys for traffic analysis and evidence extraction.",
    capabilityPacks: ["wifi","evidence"],
    recommendedAgents: ["network-testing-specialist","evidence-specialist","wifi-specialist"],
    executionModel: "skills-and-tools",
    netRunnerTools: ["Bash","TodoWrite","Write","Read"],
    requiredCommands: ["airdecap-ng"],
  },
]
